const currencies = [
  {
    code: "USD",
    country: "United States",
    currency: "Dollar",
    symbol: "$",
    flag: "🇺🇸",
  },
  { code: "CNY", country: "China", currency: "Yuan", symbol: "¥", flag: "🇨🇳" },
  { code: "JPY", country: "Japan", currency: "Yen", symbol: "¥", flag: "🇯🇵" },
  {
    code: "EUR",
    country: "Eurozone",
    currency: "Euro",
    symbol: "€",
    flag: "🇪🇺",
  },
  {
    code: "GBP",
    country: "United Kingdom",
    currency: "Pound Sterling",
    symbol: "£",
    flag: "🇬🇧",
  },
  {
    code: "BRL",
    country: "Brazil",
    currency: "Real",
    symbol: "R$",
    flag: "🇧🇷",
  },
  {
    code: "CAD",
    country: "Canada",
    currency: "Canadian Dollar",
    symbol: "CA$",
    flag: "🇨🇦",
  },
  {
    code: "AUD",
    country: "Australia",
    currency: "Australian Dollar",
    symbol: "A$",
    flag: "🇦🇺",
  },
  {
    code: "MXN",
    country: "Mexico",
    currency: "Mexican Peso",
    symbol: "Mex$",
    flag: "🇲🇽",
  },
  {
    code: "KRW",
    country: "South Korea",
    currency: "South Korean Won",
    symbol: "₩",
    flag: "🇰🇷",
  },
  {
    code: "INR",
    country: "India",
    currency: "Indian Rupee",
    symbol: "₹",
    flag: "🇮🇳",
  },
  {
    code: "RUB",
    country: "Russia",
    currency: "Russian Ruble",
    symbol: "₽",
    flag: "🇷🇺",
  },
  {
    code: "IDR",
    country: "Indonesia",
    currency: "Indonesian Rupiah",
    symbol: "Rp",
    flag: "🇮🇩",
  },
  {
    code: "ZAR",
    country: "South Africa",
    currency: "South African Rand",
    symbol: "R",
    flag: "🇿🇦",
  },
  {
    code: "TRY",
    country: "Turkey",
    currency: "Turkish Lira",
    symbol: "₺",
    flag: "🇹🇷",
  },
  {
    code: "SEK",
    country: "Sweden",
    currency: "Swedish Krona",
    symbol: "kr",
    flag: "🇸🇪",
  },
  {
    code: "PLN",
    country: "Poland",
    currency: "Polish Zloty",
    symbol: "zł",
    flag: "🇵🇱",
  },
  {
    code: "ARS",
    country: "Argentina",
    currency: "Argentine Peso",
    symbol: "$",
    flag: "🇦🇷",
  },
  {
    code: "THB",
    country: "Thailand",
    currency: "Thai Baht",
    symbol: "฿",
    flag: "🇹🇭",
  },
  {
    code: "AED",
    country: "United Arab Emirates",
    currency: "UAE Dirham",
    symbol: "د.إ",
    flag: "🇦🇪",
  },
  {
    code: "NGN",
    country: "Nigeria",
    currency: "Nigerian Naira",
    symbol: "₦",
    flag: "🇳🇬",
  },
  {
    code: "EGP",
    country: "Egypt",
    currency: "Egyptian Pound",
    symbol: "E£",
    flag: "🇪🇬",
  },
  {
    code: "COP",
    country: "Colombia",
    currency: "Colombian Peso",
    symbol: "COL$",
    flag: "🇨🇴",
  },
  {
    code: "SGD",
    country: "Singapore",
    currency: "Singapore Dollar",
    symbol: "S$",
    flag: "🇸🇬",
  },
  {
    code: "MYR",
    country: "Malaysia",
    currency: "Malaysian Ringgit",
    symbol: "RM",
    flag: "🇲🇾",
  },
  {
    code: "ILS",
    country: "Israel",
    currency: "Israeli Shekel",
    symbol: "₪",
    flag: "🇮🇱",
  },
  {
    code: "PHP",
    country: "Philippines",
    currency: "Philippine Peso",
    symbol: "₱",
    flag: "🇵🇭",
  },
  {
    code: "IEP",
    country: "Ireland",
    currency: "Euro",
    symbol: "€",
    flag: "🇮🇪",
  },
  {
    code: "DKK",
    country: "Denmark",
    currency: "Danish Krone",
    symbol: "kr",
    flag: "🇩🇰",
  },
  {
    code: "NOK",
    country: "Norway",
    currency: "Norwegian Krone",
    symbol: "kr",
    flag: "🇳🇴",
  },
  {
    code: "CZK",
    country: "Czech Republic",
    currency: "Czech Koruna",
    symbol: "Kč",
    flag: "🇨🇿",
  },
  {
    code: "MAD",
    country: "Morocco",
    currency: "Moroccan Dirham",
    symbol: "DH",
    flag: "🇲🇦",
  },
  {
    code: "IRR",
    country: "Iran",
    currency: "Iranian Rial",
    symbol: "﷼",
    flag: "🇮🇷",
  },
  {
    code: "NZD",
    country: "New Zealand",
    currency: "New Zealand Dollar",
    symbol: "NZ$",
    flag: "🇳🇿",
  },
  {
    code: "HUF",
    country: "Hungary",
    currency: "Hungarian Forint",
    symbol: "Ft",
    flag: "🇭🇺",
  },
  {
    code: "PEN",
    country: "Peru",
    currency: "Peruvian Sol",
    symbol: "S/.",
    flag: "🇵🇪",
  },
  {
    code: "VEF",
    country: "Venezuela",
    currency: "Venezuelan Bolívar",
    symbol: "Bs.",
    flag: "🇻🇪",
  },
];

export const getCurrency = (code: string) => {
  return currencies.find((currency) => currency.code === code);
};

export const getCurrencies = () => {
  return currencies;
};
